chzuoj:
    #数据库相关
    database:
        host: localhost
        port: 3306
        name: jol
        username: jol
        password: root
    #OJ名称
    name: 滁州学院在线评测系统
    #主页路径
    home: ./
    #管理员的邮箱
    admin-mail: root@localhost
    #题目数据路径
    datapath: /home/judge/data
    #是否开启在线功能
    online: false
    #语言
    language: cn
    #是否开启相似度检查
    sim: true
    #是否开启翻译功能
    dict: false
    #OJ支持的语言，此值为以下数字的和：1代表C，2代表C++， 4代表Pascal，8代表Java，16代表Ruby，32代表Bash，64代表Python，128代表PHP，256代表Perl，512代表C#，1024代表Objective-C，2048代表FreeBasic
    #4096代表Scheme，8192代表Clang，16384代表Clang++，32768代表Lua，65536代表JavaScript，131072代表其他语言
    language-mask: 262132
    #启用现场赛状态，填写现场赛比赛ID，不填写代表不启用
    on-site-contest-id: 
    #cdn加速的域名
    cdn-url: 
    #网站使用的css文件名
    css: hznu.css
server:
    port: 8080
    servlet:
        session:
            timeout: 30m
    tomcat:
        uri-encoding: utf-8
spring:
    application:
        name: chzuoj
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://${chzuoj.database.host}:${chzuoj.database.port}/${chzuoj.database.name}?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8"
        username: "${chzuoj.database.username}"
        password: "${chzuoj.database.password}"
        initial-size: 5
        min-idle: 5
        max-idle: 10
        max-wait: 10000
    thymeleaf:
        #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
        mode: HTML5
        #编码 可不用配置
        encoding: UTF-8
        #内容类别,可不用配置
        content-type: text/html
        #开发配置为false,避免修改模板还要重启服务器
        cache: false