server:
    port: 8080
    servlet:
        session:
            timeout: 30m
    tomcat:
        uri-encoding: utf-8
spring:
    application:
        name: chzuoj
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/jol?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: jol
        password: root
        initial-size: 5
        min-idle: 5
        max-idle: 10
        max-wait: 10000
    thymeleaf:
        #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
        mode: HTML5
        #编码 可不用配置
        encoding: UTF-8
        #内容类别,可不用配置
        content-type: text/html
        #开发配置为false,避免修改模板还要重启服务器
        cache: false